import {RFValue} from 'react-native-responsive-fontsize';

const Theme = {
  colors: {
    appColorTutor: '#1E71B7',
    appColorStudent: '#E14E96',
    appColorParent: '#1D9A7A',
    appColorLight: '#A3A4A9',
    inputBackground: '#EAEAEA',
    notAttended: '#6E3B8F', //Calendar
    delivered_approved: '#02A9DD', //Calendar
    pending: '#FF8A00', //Calendar
    planned_online: '#2DA98A', //Calendar
    planned_face: '#FFCE3A', //Calendar
    red_notification: '#F72020',
    disabled: '#BFBFBF',
    white: '#FFFFFF',
    black: '#000000',
    transparent: 'transparent',
    placeholderColor: '#C4C4C4',

    bgColor1: '#1525A3',
    bgColor2: '#FFFFFF',
    bgHeading1: '#F8F1DD',
    bgHeading2: '#DDF1EC',

    sheetMessageColor: '#E6F5F1',
    bgColor35: '#F8F1DD',
    bgColor36: '#DDF1EC',
    bgColor37: '#FFDDDD',

    // transparency colors
    transColor1: '#ffffff7a',

    textColor1: '#FFFFFF',
    textColor2: '#000000',
    textColor3: '#1525A3',
    textColor4: '#656565',
    textColor29: '#03192C',
    textColor30: '#02A9DD',
  },
  fontFamily: {
    // Poppins
    fontPoppinsBlack: 'Poppins-Black',
    fontPoppinsBlackItalic: 'Poppins-BlackItalic',
    fontPoppinsBold: 'Poppins-Bold',
    fontPoppinsBoldItalic: 'Poppins-BoldItalic',
    fontPoppinsExtraBold: 'Poppins-ExtraBold',
    fontPoppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
    fontPoppinsExtraLight: 'Poppins-ExtraLight',
    fontPoppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
    fontPoppinsItalic: 'Poppins-Italic',
    fontPoppinsLight: 'Poppins-Light',
    fontPoppinsLightItalic: 'Poppins-LightItalic',
    fontPoppinsMedium: 'Poppins-Medium',
    fontPoppinsMediumItalic: 'Poppins-MediumItalic',
    fontPoppinsRegular: 'Poppins-Regular',
    fontPoppinsSemiBold: 'Poppins-SemiBold',
    fontPoppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
    fontPoppinsThin: 'Poppins-Thin',
    fontPoppinsThinItalic: 'Poppins-ThinItalic',
  },
  responsiveSize: {
    size1: RFValue(1),
    size2: RFValue(2),
    size3: RFValue(3),
    size4: RFValue(4),
    size5: RFValue(5),
    size6: RFValue(6),
    size7: RFValue(7),
    size8: RFValue(8),
    size9: RFValue(9),
    size10: RFValue(10),
    size11: RFValue(11),
    size12: RFValue(12),
    size13: RFValue(13),
    size14: RFValue(14),
    size15: RFValue(15),
    size16: RFValue(16),
    size17: RFValue(17),
    size18: RFValue(18),
    size19: RFValue(19),
    size20: RFValue(20),
    size21: RFValue(21),
    size22: RFValue(22),
    size24: RFValue(24),
    size25: RFValue(25),
    size26: RFValue(26),
    size28: RFValue(28),
    size30: RFValue(30),
    size32: RFValue(32),
    size35: RFValue(35),
    size36: RFValue(36),
    size38: RFValue(38),
    size40: RFValue(40),
    size42: RFValue(42),
    size43: RFValue(43),
    size45: RFValue(45),
    size47: RFValue(47),
    size48: RFValue(48),
    size50: RFValue(50),
    size52: RFValue(52),
    size54: RFValue(54),
    size55: RFValue(55),
    size60: RFValue(60),
    size63: RFValue(63),
    size65: RFValue(65),
    size70: RFValue(70),
    size75: RFValue(75),
    size78: RFValue(78),
    size80: RFValue(80),
    size85: RFValue(85),
    size90: RFValue(90),
    size95: RFValue(95),
    size100: RFValue(100),
    size105: RFValue(105),
    size110: RFValue(110),
    size115: RFValue(115),
    size118: RFValue(118),
    size120: RFValue(120),
    size122: RFValue(122),
    size124: RFValue(124),
    size125: RFValue(125),
    size130: RFValue(130),
    size135: RFValue(135),
    size140: RFValue(140),
    size150: RFValue(150),
    size160: RFValue(160),
    size170: RFValue(170),
    size177: RFValue(177),
    size180: RFValue(180),
    size190: RFValue(190),
    size200: RFValue(200),
    size210: RFValue(210),

    size220: RFValue(220),
    size230: RFValue(230),
    size240: RFValue(240),
    size250: RFValue(250),
    size255: RFValue(255),
    size260: RFValue(260),
    size280: RFValue(280),
    size285: RFValue(285),
    size300: RFValue(300),
    size320: RFValue(320),
    size350: RFValue(350),
  },
  icons: {
    // not used
    splash_logo: require('../resources/images/splash.png'),
    splash_background: require('../resources/images/splash-background.png'),
    parent_home: require('../resources/images/parent-home.png'),
    parent_home_active: require('../resources/images/parent-home-active.png'),
    parent_home_lessons_active: require('../resources/images/parent-home-lessons-active.png'),
    parent_home_lessons: require('../resources/images/parent-home-lessons.png'),
    parent_calendar: require('../resources/images/parent-calendar.png'),
    parent_calendar_active: require('../resources/images/parent-calendar-active.png'),
    parent_lessons: require('../resources/images/parent-lessons.png'),
    parent_lessons_active: require('../resources/images/parent-lessons-active.png'),
    parent_training: require('../resources/images/parent-training.png'),
    parent_training_active: require('../resources/images/parent-training-active.png'),
    parent_profile: require('../resources/images/parent-profile.png'),
    parent_profile_active: require('../resources/images/parent-profile-active.png'),
    tutor_students: require('../resources/images/tutor-students.png'),
    tutor_students_active: require('../resources/images/tutor-students-active.png'),
    tutor_incidents: require('../resources/images/tutor-incidents.png'),
    tutor_incidents_active: require('../resources/images/tutor-incidents-active.png'),
    more: require('../resources/images/more.png'),
    more_active: require('../resources/images/more-active.png'),
    home_lesson: require('../resources/images/home-lesson.png'),
    home_lesson_active: require('../resources/images/home-lesson-active.png'),
    home_tracking: require('../resources/images/home-tracking.png'),
    home_tracking_active: require('../resources/images/home-tracking-active.png'),
    timer: require('../resources/images/timer.png'),
    send_message: require('../resources/images/send-message.png'),
    navigation: require('../resources/images/navigation.png'),
    map: require('../resources/images/map.png'),
    sos: require('../resources/images/sos.png'),
    student_arrive: require('../resources/images/student-arrive.png'),
    add_incident: require('../resources/images/add-incident.png'),
    end_lesson: require('../resources/images/end-lesson.png'),
    lessons_calendar: require('../resources/images/lessons-calendar.png'),
    lessons_calendar_active: require('../resources/images/lessons-calendar-active.png'),
    lessons_lessons: require('../resources/images/lessons-lessons.png'),
    lessons_lessons_active: require('../resources/images/lessons-lessons-active.png'),
    Child1: require('../resources/images/Child1.png'),
    Child2: require('../resources/images/Child2.png'),
    Child3: require('../resources/images/Child3.png'),
    tutor_calendar: require('../resources/images/tutor-Calendar.png'),
    tutor_Clock: require('../resources/images/tutor-Clock.png'),
    tutor_Location: require('../resources/images/tutor-Location.png'),
    NextBtn: require('../resources/images/NextBtn.png'),
    red_Clock: require('../resources/images/redClock.png'),
    tick: require('../resources/images/tick.png'),
    edit_Pencil: require('../resources/images/editPencil.png'),
    notification: require('../resources/images/notification.png'),
    profileTraining: require('../resources/images/profileTraining.png'),
    goBack: require('../resources/images/goBack.png'),
    upCommingNotification: require('../resources/images/upComingNotification.png'),
    time_Duration: require('../resources/images/timeDuration.png'),
    lesson_Icon: require('../resources/images/lessonIcon.png'),
    target_Loaction:require('../resources/images/targetLoaction.png'),
    default:require('../resources/images/default.png')
  },
};

export default Theme;
